services:

  mailpit:
    image: axllent/mailpit:latest
    environment:
      - TZ=UTC
      - MP_MAX_AGE=7d
    volumes:
      - mailpit-data:/data
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port

volumes:
  mailpit-data: